### ISSUE TITLE
Data Tables - BCI table caption edits

### ISSUE THREAD

**Issue by ermnmatt** [NCRN/BirdViz#72]
The captions for both the upper and lower tables need some edits. Some are associated with dynamic updates to the caption and other are just typos.

Upper table caption:
There should be a space rather than a dot after "during". 
The spelling of "deteections" should be fixed.
Add an "i" to the word "is".
Fix spelling of "assinged".
There should be a comma instead of a dot after "Medium"

Lower table caption:
There should be a comma instead of a dot after "Medium"
The spelling of "integiry" should be fixed.

**Comment by aaronweed** [comment]
all of these have been updated.I will commit to master.
